name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8 autopep8 autoflake
        pip install fastapi uvicorn mlflow pandas httpx scikit-learn
    # Step 3.1: Auto-format code
    - name: Format code
      run: |
        autopep8 --in-place --recursive --aggressive --aggressive .
        autoflake --in-place --remove-unused-variables --remove-all-unused-imports --recursive .

    # Step 4: Lint
    - name: Run lint
      run: |
        flake8 .

    # Step 5: Run tests
    - name: Run tests
      run: |
        pytest tests/ --maxfail=1 --disable-warnings -q

    # Step 6: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Step 7: Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: priyamtiwarigenai/mlflow-server:latest

    # Step 8: Deploy (Local/EC2)
    - name: Deploy container
      run: |
        chmod +x deploy.sh
        ./deploy.sh
